### ISSUE TITLE
Do you have contact details to the winners of recent Ethereum Hackathon in Berlin who are hiring in London?

### ISSUE THREAD

**Issue by marsrobertson** [Department-of-Decentralization/Ecosystem-Job-Openings#34]
I believe it is better to apply for a job directly, looking for contact details.

The link below is to a job advert.

The job does not mention Ethereum as required technology.

It mentions that team has won the hackathon - I would like contact them directly, as opposed to going through recruiter.

**That's why asking for contact details.**

------

From the job advert: http://www.jobserve.com/GqRGg

<img width="792" alt="screenshot 2019-01-02 at 14 11 32" src="https://user-images.githubusercontent.com/44369284/50593391-79099600-0e98-11e9-8777-f75a7784998c.png">

I did some research, endless scrolling throught the Twitter feed:
* https://twitter.com/ETHBerlin/status/1038809132231479296
* https://twitter.com/ETHBerlin/status/1038803516511473664
* https://twitter.com/ETHBerlin/status/1038806770888704002
* https://twitter.com/ETHBerlin/status/1038808843143335936

Maybe you'll know?

**Comment by mariapaulafn** [comment]
Hello, we don't provide contact details of any hacker. I RTd your request, to see if someone picks it up, but that's the only thing I can do. 
If the team is willing to disclose, they can make a PR in our jobs repo, and we'll approve. We don't approve recruiting agencies
