### ISSUE TITLE
Should recruiter add job as an issue instead of PR ?

### ISSUE THREAD

**Issue by TanNgocDo** [Department-of-Decentralization/Ecosystem-Job-Openings#40]
Refer to this : https://github.com/awesome-jobs/vietnam. If company wants to create a new job, they only needs to raise an issue.

**Comment by mariapaulafn** [comment]
Hello, we are not accepting recruiters. Sorry. Only companies getting in touch with individuals

**Comment by mariapaulafn** [comment]
In case you're suggesting another way to do things - then, thanks for the suggestion but this is our way, and it's all good. We ask for PRs because we review them to avoid recruiters.
